apiVersion: v2
name: onboarding-pgtec
description: A Helm chart for the Onboarding Portal of the PGTEC data space
type: application
version: 0.1.0
appVersion: "0.1"
maintainers:
  - name: "Sergio Marti"
    email: "sermars7@upv.es"
keywords:
  - onboarding
  - portal
  - pgtec
  - fiware-data-space
