database:
  type: postgres
  host: db
  port: 5432
  username: onboarding
  password: onboarding
  database: onboarding
  synchronize: true
  logging: false

app:
  browserTitle: "${APP_BROWSER_TITLE}"
  enableThemeToggle: "${APP_ENABLE_THEME_TOGGLE}"
  documentToSignUrl: "https://onboarding-docs.pgtec-vrain-dataspace.eu/documents/onboarding/agreement.pdf"
  projectWebsiteUrl: "https://pgtec.webs.upv.es/"
  marketplaceUrl: "${APP_MARKETPLACE_URL}"
  keycloakAdminUrl: "${APP_KEYCLOAK_ADMIN_URL}"
  tir:
    url: "https://example.com/issuer"
  login:
    openIdUrl: "https://example.com"
    clientId: "local-dev"
    clientSecret: ""

email:
  enabled: false
